site_name: Threadwalker
site_url: https://ingannamortesciencedev.github.io/Threadwalker-Docs/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: blue
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - i18n:
      default_language: en
      default_language_only: true
      languages:
        en:
          name: English
          build: true
        ru:
          name: Русский
          build: true
        ja:
          name: 日本語
          build: true
        zh:
          name: 中文
          build: true