site_name: Threadwalker
site_url: https://ingannamortesciencedev.github.io/Threadwalker-Docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: blue
      accent: blue
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        ru: Русский
        ja: 日本語
        zh: 中文

nav:
  - Home: index.md
